# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:18.2.0
    steps:
      - checkout
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Check style
          command: yarn prettier-check .
      - run:
          name: Build files
          command: yarn build

workflows:
  build:
    jobs:
      - build
